function wyswietl_dane(xs,ys,m,L,d,k,e_b,g,t_max)
disp('  ')
disp('Parametry zadania:')
fprintf('   Współrzędna początkowa x skoczka, xs = %0.2f m \n', xs)
fprintf('   Współrzędna początkowa y skoczka, ys = %0.2f m \n', ys)
fprintf('   Masa skoczka, m = %0.2f kg \n', m)
fprintf('   Długość liny bungee, L = %0.2f m \n', L)
fprintf('   Współczynnik oporów ruchu, d = %0.2f N*s2/m2 \n', d)
fprintf('   Paramterty sztywności liny: \n')
fprintf('       k(1) = %0.2f N/m \n', k(1))
fprintf('       k(2) = %0.2f N/m \n', k(2))
fprintf('       e_b  = %0.2f m \n', e_b)
fprintf('   Przyspieszenie grawitacyjne, g = %0.2f m/s2 \n', g)
fprintf('   Czas lotu, t_max = %0.2f s \n', t_max)
disp('  ')
end
